### ISSUE TITLE
Title: Tiers library

### ISSUE THREAD

**Issue by DavidLari** [terflogag/OpenSourceController#3]
There doesn't seem to be a way to change the title on the view controller and "Tier library" is hard coded. Also, the text color and background colors are not exposed publicly. It would be nice to have control over these as properties on OpenSourceController.

**Comment by floriangbh** [comment]
Hello ! 

I just tried in another project to set `"Tiers library" = "Blabla";` in my Localizable.string file and it work fine ! 
Did you override NSLocalizedString in your project ? 
How is set the title : `NSLocalizedString("Tiers library", comment: "")`

For the customization I'll make it asap, probably this afternoon for the next version, thank you !

**Comment by floriangbh** [comment]
Just pushed v1.0.5 on cocoapods. 
See the https://github.com/terflogag/OpenSourceController#customisation section :-)

**Comment by DavidLari** [comment]
Wow! You are awesome! Thanks so much for sharing this in the first place, and also for so quickly adding the configuration features. Very nice!
